POST   http://localhost:3001/api/evaluations
Content-Type: application/json

{
  "email": "pepitalapistolera@gmail.com",
  "evaluation": "actualizado",
  "segment": "actualizado",
  "csvFile": {
    "csvData": "Time",
    "contentType": "text/csv"
  }
}
###
POST   http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "juan",
  "name": "juan",
  "password": "1234"
}