PUT http://localhost:3001/api/evaluations/6328ae8166cb72d43562eb23
Content-Type: application/json

{
    "email": "pepitalapistolera@gmail.com",
    "evaluation": "actualizado",
    "segment": "actualizado",
    "csvFile": {
      "csvData": "Time",
      "contentType": "text/csv"
    },
};