PUT http://localhost:3001/api/evaluations/6335b7e14132c57f097a9154
Content-Type: application/json

{
  "email": "pepitalapistolera@gmail.com",
  "evaluation": "actualizado",
  "segment": "actualizado",
  "csvFile": {
      "csvData": "Time",
      "contentType": "text/csv"
  },
};